#ifndef SCANCODES_H
#define SCANCODES_H

#include <os/keys.h>
/*
unsigned char at_scancodes[] = { VK_NULL, VK_F9, VK_NULL, VK_F5, VK_F3, VK_F1, 
VK_F2, VK_F12, VK_NULL, VK_F10, VK_F8, VK_F6, VK_F4, VK_TAB, 
VK_BQUOTE,VK_NULL,VK_NULL,VK_LALT, 
VK_LSHIFT, VK_NULL, VK_LCTRL, VK_Q, VK_1, VK_NULL,VK_NULL,VK_NULL,VK_Z, 
*/

unsigned char xt_scancodes[] = { VK_NULL, VK_ESC, VK_1, VK_2, VK_3, VK_4, VK_5, VK_6, 
  VK_7, VK_8, VK_9, VK_0, VK_MINUS, VK_EQUAL, VK_BSPACE, VK_TAB, VK_Q, 
  VK_W, VK_E, VK_R, VK_T, VK_Y, VK_U, VK_I, VK_O, VK_P, VK_LBRACK, 
  VK_RBRACK, VK_ENTER, VK_LCTRL, VK_A, VK_S, VK_D, VK_F, VK_G, VK_H, VK_J, 
  VK_K, VK_L, VK_SEMICOL, VK_QUOTE, VK_BQUOTE, VK_LSHIFT, VK_BSLASH, VK_Z, 
  VK_X, VK_C, VK_V, VK_B, VK_N, VK_M, VK_COMMA, VK_PERIOD, VK_SLASH, 
  VK_RSHIFT, VK_NULL, VK_LALT, VK_SPACE, VK_CAPSLK, VK_F1, VK_F2, 
  VK_F3, VK_F4, VK_F5, VK_F6, VK_F7, VK_F8, VK_F9, VK_F10,  VK_NUMLK, 
  VK_SCRLK, VK_KP_7, VK_KP_8, VK_KP_9, VK_KP_MINUS, VK_KP_4,
  VK_KP_5, VK_KP_6, VK_KP_PLUS, VK_KP_1, VK_KP_2, VK_KP_3, VK_KP_0, 
  VK_KP_PERIOD, VK_NULL, VK_NULL, VK_OCTHRP, VK_F11, VK_F12 
};

#endif /* SCANCODES_H */
