SRC     =time.c mktime.c gmtime.c asctime.c _time.c difftime.c\
	ctime.c
OBJ     =$(SRC:.c=.o)
OPT_FLG =-O2
CLEAN   =$(OBJ)

all: $(OBJ)

include ../../vars.mk
# DO NOT DELETE

time.o: /home/tiju/silverbox-os/include/time.h
time.o: /home/tiju/silverbox-os/include/types.h
time.o: /home/tiju/silverbox-os/include/stddef.h
time.o: /home/tiju/silverbox-os/include/stdbool.h
time.o: /home/tiju/silverbox-os/include/os/variables.h
gmtime.o: /home/tiju/silverbox-os/include/time.h
gmtime.o: /home/tiju/silverbox-os/include/types.h
gmtime.o: /home/tiju/silverbox-os/include/stddef.h
gmtime.o: /home/tiju/silverbox-os/include/stdbool.h
asctime.o: /home/tiju/silverbox-os/include/time.h
asctime.o: /home/tiju/silverbox-os/include/types.h
asctime.o: /home/tiju/silverbox-os/include/stddef.h
asctime.o: /home/tiju/silverbox-os/include/stdbool.h
asctime.o: /home/tiju/silverbox-os/include/stdio.h
asctime.o: /home/tiju/silverbox-os/include/stdarg.h
_time.o: /home/tiju/silverbox-os/include/time.h
_time.o: /home/tiju/silverbox-os/include/types.h
_time.o: /home/tiju/silverbox-os/include/stddef.h
_time.o: /home/tiju/silverbox-os/include/stdbool.h
difftime.o: /home/tiju/silverbox-os/include/time.h
difftime.o: /home/tiju/silverbox-os/include/types.h
difftime.o: /home/tiju/silverbox-os/include/stddef.h
difftime.o: /home/tiju/silverbox-os/include/stdbool.h
ctime.o: /home/tiju/silverbox-os/include/time.h
ctime.o: /home/tiju/silverbox-os/include/types.h
ctime.o: /home/tiju/silverbox-os/include/stddef.h
ctime.o: /home/tiju/silverbox-os/include/stdbool.h
