SRC     =shell.c
OUTPUT  =shell.exe

include ../apps.mk
# DO NOT DELETE

shell.o: /home/tiju/Silverbox-OS/include/oslib.h
shell.o: /home/tiju/Silverbox-OS/include/types.h
shell.o: /home/tiju/Silverbox-OS/include/stddef.h
shell.o: /home/tiju/Silverbox-OS/include/stdbool.h
shell.o: /home/tiju/Silverbox-OS/include/ipc.h
shell.o: /home/tiju/Silverbox-OS/include/os/mutex.h
shell.o: /home/tiju/Silverbox-OS/include/string.h
shell.o: /home/tiju/Silverbox-OS/include/os/dev_interface.h
shell.o: /home/tiju/Silverbox-OS/include/os/variables.h
shell.o: /home/tiju/Silverbox-OS/include/ctype.h
shell.o: /home/tiju/Silverbox-OS/include/os/vfs.h
shell.o: /home/tiju/Silverbox-OS/include/os/file.h
shell.o: /home/tiju/Silverbox-OS/include/os/services.h
shell.o: /home/tiju/Silverbox-OS/include/os/device.h
shell.o: /home/tiju/Silverbox-OS/include/os/region.h
shell.o: /home/tiju/Silverbox-OS/include/os/fatfs.h
shell.o: /home/tiju/Silverbox-OS/include/stdlib.h
shell.o: /home/tiju/Silverbox-OS/include/stdio.h
shell.o: /home/tiju/Silverbox-OS/include/stdarg.h
shell.o: /home/tiju/Silverbox-OS/include/time.h
