SRC     =shell.c
OUTPUT  =shell.exe

include ../apps.mk
# DO NOT DELETE

shell.o: /home/tiju/silverbox-os/include/oslib.h
shell.o: /home/tiju/silverbox-os/include/types.h
shell.o: /home/tiju/silverbox-os/include/stddef.h
shell.o: /home/tiju/silverbox-os/include/stdbool.h
shell.o: /home/tiju/silverbox-os/include/ipc.h
shell.o: /home/tiju/silverbox-os/include/os/mutex.h
shell.o: /home/tiju/silverbox-os/include/string.h
shell.o: /home/tiju/silverbox-os/include/os/dev_interface.h
shell.o: /home/tiju/silverbox-os/include/os/vfs.h
shell.o: /home/tiju/silverbox-os/include/os/file.h
shell.o: /home/tiju/silverbox-os/include/os/services.h
shell.o: /home/tiju/silverbox-os/include/os/device.h
shell.o: /home/tiju/silverbox-os/include/os/region.h
shell.o: /home/tiju/silverbox-os/include/stdlib.h
shell.o: /home/tiju/silverbox-os/include/stdio.h
shell.o: /home/tiju/silverbox-os/include/stdarg.h
