SRC     =cqueue.c
OBJ     =$(SRC:.c=.o)
OPT_FLG =-O0
CLEAN   =$(OBJ)

all: $(OBJ)

include ../../../vars.mk
# DO NOT DELETE

cqueue.o: /home/tiju/silverbox-os/include/os/adt/cqueue.h
cqueue.o: /home/tiju/silverbox-os/include/stddef.h
cqueue.o: /home/tiju/silverbox-os/include/stdlib.h
cqueue.o: /home/tiju/silverbox-os/include/string.h
