SRC     =cqueue.c sbarray.c sbassocarray.c sbstring.c
OBJ     =$(SRC:.c=.o)
OPT_FLG =-O0
CLEAN   =$(OBJ)

all: $(OBJ)

include ../../../vars.mk
# DO NOT DELETE

cqueue.o: /home/tiju/Silverbox-OS/include/os/ostypes/cqueue.h
cqueue.o: /home/tiju/Silverbox-OS/include/stddef.h
cqueue.o: /home/tiju/Silverbox-OS/include/stdlib.h
cqueue.o: /home/tiju/Silverbox-OS/include/string.h
sbarray.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
sbarray.o: /home/tiju/Silverbox-OS/include/string.h
sbarray.o: /home/tiju/Silverbox-OS/include/stddef.h
sbarray.o: /home/tiju/Silverbox-OS/include/stdlib.h
sbarray.o: /home/tiju/Silverbox-OS/include/stdarg.h
sbassocarray.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h
sbassocarray.o: /home/tiju/Silverbox-OS/include/stdlib.h
sbassocarray.o: /home/tiju/Silverbox-OS/include/stddef.h
sbassocarray.o: /home/tiju/Silverbox-OS/include/string.h
sbstring.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
sbstring.o: /home/tiju/Silverbox-OS/include/stdlib.h
sbstring.o: /home/tiju/Silverbox-OS/include/stddef.h
sbstring.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
sbstring.o: /home/tiju/Silverbox-OS/include/string.h
