include ../prefix.inc

DIRS	=rtc init_server

.PHONY:	$(DIRS) $(DEF_PHONY)

all:	$(DIRS)

init_server:
	make -C $@ all

rtc:
	make -C $@ all

install: $(DIRS)
	for i in $(DIRS); do make -C $$i install; done

depend:
	for i in $(DIRS); do make -C $$i depend; done

clean:
	rm -f *.o
	rm -f *.dmp
	rm -f *.dbg
	rm -f *.exe
	for i in $(DIRS); do make -C $$i clean; done

include ../Makefile.inc
include ../vars.mk

