DIRS	=fs
SRC     =addr_space.c phys_alloc.c initsrv.c name.c \
	exceptions.c sbrk.c init.c paging.c resources.c \
	fs/vfs.c fs/fat_lib.c fs/fat_fs.c fs/fat_alloc.c \
	fs/vfs_ops.c

OUTPUT	=pagersrv.exe
INSTALL_DIR=programs/

include apps.mk

# DO NOT DELETE

addr_space.o: addr_space.h /home/tiju/Silverbox-OS/include/os/region.h
addr_space.o: /home/tiju/Silverbox-OS/include/stddef.h
addr_space.o: /home/tiju/Silverbox-OS/include/stdbool.h
addr_space.o: /home/tiju/Silverbox-OS/include/oslib.h
addr_space.o: /home/tiju/Silverbox-OS/include/types.h
addr_space.o: /home/tiju/Silverbox-OS/include/ipc.h
addr_space.o: /home/tiju/Silverbox-OS/include/os/mutex.h
addr_space.o: /home/tiju/Silverbox-OS/include/os/bitmap.h
addr_space.o: /home/tiju/Silverbox-OS/include/os/os_types.h
addr_space.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
addr_space.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
addr_space.o: /home/tiju/Silverbox-OS/include/stdlib.h
addr_space.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h
addr_space.o: phys_alloc.h initsrv.h resources.h paging.h
phys_alloc.o: phys_alloc.h initsrv.h addr_space.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/os/region.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/stddef.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/stdbool.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/oslib.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/types.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/ipc.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/os/mutex.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/os/bitmap.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/os/os_types.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/stdlib.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h
phys_alloc.o: resources.h paging.h /home/tiju/Silverbox-OS/include/string.h
initsrv.o: /home/tiju/Silverbox-OS/include/oslib.h
initsrv.o: /home/tiju/Silverbox-OS/include/types.h
initsrv.o: /home/tiju/Silverbox-OS/include/stddef.h
initsrv.o: /home/tiju/Silverbox-OS/include/stdbool.h
initsrv.o: /home/tiju/Silverbox-OS/include/ipc.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/mutex.h
initsrv.o: /home/tiju/Silverbox-OS/include/string.h
initsrv.o: /home/tiju/Silverbox-OS/include/stdlib.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/services.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/device.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/region.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/message.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/dev_interface.h paging.h
initsrv.o: addr_space.h /home/tiju/Silverbox-OS/include/os/bitmap.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/os_types.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h name.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/vfs.h
initsrv.o: /home/tiju/Silverbox-OS/include/os/file.h resources.h shmem.h
name.o: /home/tiju/Silverbox-OS/include/oslib.h
name.o: /home/tiju/Silverbox-OS/include/types.h
name.o: /home/tiju/Silverbox-OS/include/stddef.h
name.o: /home/tiju/Silverbox-OS/include/stdbool.h
name.o: /home/tiju/Silverbox-OS/include/ipc.h
name.o: /home/tiju/Silverbox-OS/include/os/mutex.h
name.o: /home/tiju/Silverbox-OS/include/os/services.h
name.o: /home/tiju/Silverbox-OS/include/os/device.h
name.o: /home/tiju/Silverbox-OS/include/os/region.h
name.o: /home/tiju/Silverbox-OS/include/os/os_types.h
name.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
name.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
name.o: /home/tiju/Silverbox-OS/include/stdlib.h
name.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h
name.o: /home/tiju/Silverbox-OS/include/string.h name.h
name.o: /home/tiju/Silverbox-OS/include/os/vfs.h
name.o: /home/tiju/Silverbox-OS/include/os/file.h
exceptions.o: addr_space.h /home/tiju/Silverbox-OS/include/os/region.h
exceptions.o: /home/tiju/Silverbox-OS/include/stddef.h
exceptions.o: /home/tiju/Silverbox-OS/include/stdbool.h
exceptions.o: /home/tiju/Silverbox-OS/include/oslib.h
exceptions.o: /home/tiju/Silverbox-OS/include/types.h
exceptions.o: /home/tiju/Silverbox-OS/include/ipc.h
exceptions.o: /home/tiju/Silverbox-OS/include/os/mutex.h
exceptions.o: /home/tiju/Silverbox-OS/include/os/bitmap.h
exceptions.o: /home/tiju/Silverbox-OS/include/os/os_types.h
exceptions.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
exceptions.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
exceptions.o: /home/tiju/Silverbox-OS/include/stdlib.h
exceptions.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h
exceptions.o: phys_alloc.h initsrv.h resources.h paging.h
exceptions.o: /home/tiju/Silverbox-OS/include/string.h
sbrk.o: /home/tiju/Silverbox-OS/include/oslib.h
sbrk.o: /home/tiju/Silverbox-OS/include/types.h
sbrk.o: /home/tiju/Silverbox-OS/include/stddef.h
sbrk.o: /home/tiju/Silverbox-OS/include/stdbool.h
sbrk.o: /home/tiju/Silverbox-OS/include/ipc.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/mutex.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/memory.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/services.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/device.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/region.h
init.o: initsrv.h addr_space.h /home/tiju/Silverbox-OS/include/os/region.h
init.o: /home/tiju/Silverbox-OS/include/stddef.h
init.o: /home/tiju/Silverbox-OS/include/stdbool.h
init.o: /home/tiju/Silverbox-OS/include/oslib.h
init.o: /home/tiju/Silverbox-OS/include/types.h
init.o: /home/tiju/Silverbox-OS/include/ipc.h
init.o: /home/tiju/Silverbox-OS/include/os/mutex.h
init.o: /home/tiju/Silverbox-OS/include/os/bitmap.h
init.o: /home/tiju/Silverbox-OS/include/os/os_types.h
init.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
init.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
init.o: /home/tiju/Silverbox-OS/include/stdlib.h
init.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h resources.h
init.o: name.h /home/tiju/Silverbox-OS/include/os/device.h
init.o: /home/tiju/Silverbox-OS/include/os/vfs.h
init.o: /home/tiju/Silverbox-OS/include/os/file.h
init.o: /home/tiju/Silverbox-OS/include/os/elf.h
init.o: /home/tiju/Silverbox-OS/include/elf.h
init.o: /home/tiju/Silverbox-OS/include/os/signal.h paging.h phys_alloc.h
init.o: shmem.h /home/tiju/Silverbox-OS/include/string.h
paging.o: /home/tiju/Silverbox-OS/include/oslib.h
paging.o: /home/tiju/Silverbox-OS/include/types.h
paging.o: /home/tiju/Silverbox-OS/include/stddef.h
paging.o: /home/tiju/Silverbox-OS/include/stdbool.h
paging.o: /home/tiju/Silverbox-OS/include/ipc.h
paging.o: /home/tiju/Silverbox-OS/include/os/mutex.h paging.h addr_space.h
paging.o: /home/tiju/Silverbox-OS/include/os/region.h
paging.o: /home/tiju/Silverbox-OS/include/os/bitmap.h
paging.o: /home/tiju/Silverbox-OS/include/os/os_types.h
paging.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
paging.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
paging.o: /home/tiju/Silverbox-OS/include/stdlib.h
paging.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h
paging.o: phys_alloc.h initsrv.h resources.h
paging.o: /home/tiju/Silverbox-OS/include/string.h
resources.o: phys_alloc.h initsrv.h addr_space.h
resources.o: /home/tiju/Silverbox-OS/include/os/region.h
resources.o: /home/tiju/Silverbox-OS/include/stddef.h
resources.o: /home/tiju/Silverbox-OS/include/stdbool.h
resources.o: /home/tiju/Silverbox-OS/include/oslib.h
resources.o: /home/tiju/Silverbox-OS/include/types.h
resources.o: /home/tiju/Silverbox-OS/include/ipc.h
resources.o: /home/tiju/Silverbox-OS/include/os/mutex.h
resources.o: /home/tiju/Silverbox-OS/include/os/bitmap.h
resources.o: /home/tiju/Silverbox-OS/include/os/os_types.h
resources.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
resources.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
resources.o: /home/tiju/Silverbox-OS/include/stdlib.h
resources.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h
resources.o: resources.h paging.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/oslib.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/types.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/stddef.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/stdbool.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/ipc.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/os/mutex.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/os/message.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/os/os_types.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbarray.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbstring.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/stdlib.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/os/ostypes/sbassocarray.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/os/vfs.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/os/file.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/string.h name.h
fs/vfs.o: /home/tiju/Silverbox-OS/include/os/device.h
