SRC     =list.c addr_space.c phys_alloc.c pagersrv.c shmem.c name.c \
	exceptions.c sbrk.c
OUTPUT	=pagersrv.exe

include ../apps.mk

# DO NOT DELETE

list.o: list.h /home/tiju/Silverbox-OS/include/stddef.h
list.o: /home/tiju/Silverbox-OS/include/stdbool.h
addr_space.o: addr_space.h /home/tiju/Silverbox-OS/include/os/bitmap.h
addr_space.o: /home/tiju/Silverbox-OS/include/stddef.h list.h
addr_space.o: /home/tiju/Silverbox-OS/include/stdbool.h phys_alloc.h
addr_space.o: pagersrv.h /home/tiju/Silverbox-OS/include/types.h
addr_space.o: /home/tiju/Silverbox-OS/include/os/region.h
phys_alloc.o: phys_alloc.h pagersrv.h /home/tiju/Silverbox-OS/include/types.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/stddef.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/stdbool.h list.h
phys_alloc.o: /home/tiju/Silverbox-OS/include/string.h
pagersrv.o: /home/tiju/Silverbox-OS/include/os/signal.h
pagersrv.o: /home/tiju/Silverbox-OS/include/oslib.h
pagersrv.o: /home/tiju/Silverbox-OS/include/types.h
pagersrv.o: /home/tiju/Silverbox-OS/include/stddef.h
pagersrv.o: /home/tiju/Silverbox-OS/include/stdbool.h
pagersrv.o: /home/tiju/Silverbox-OS/include/ipc.h
pagersrv.o: /home/tiju/Silverbox-OS/include/os/mutex.h
pagersrv.o: /home/tiju/Silverbox-OS/include/elf.h
pagersrv.o: /home/tiju/Silverbox-OS/include/string.h
pagersrv.o: /home/tiju/Silverbox-OS/include/stdlib.h
pagersrv.o: /home/tiju/Silverbox-OS/include/os/services.h
pagersrv.o: /home/tiju/Silverbox-OS/include/os/device.h
pagersrv.o: /home/tiju/Silverbox-OS/include/os/region.h
pagersrv.o: /home/tiju/Silverbox-OS/include/os/uthreads.h
pagersrv.o: /home/tiju/Silverbox-OS/include/os/message.h
pagersrv.o: /home/tiju/Silverbox-OS/include/os/dev_interface.h shmem.h
pagersrv.o: addr_space.h /home/tiju/Silverbox-OS/include/os/bitmap.h list.h
pagersrv.o: phys_alloc.h pagersrv.h name.h
shmem.o: list.h /home/tiju/Silverbox-OS/include/stddef.h
shmem.o: /home/tiju/Silverbox-OS/include/stdbool.h phys_alloc.h pagersrv.h
shmem.o: /home/tiju/Silverbox-OS/include/types.h shmem.h addr_space.h
shmem.o: /home/tiju/Silverbox-OS/include/os/bitmap.h
shmem.o: /home/tiju/Silverbox-OS/include/os/region.h
shmem.o: /home/tiju/Silverbox-OS/include/oslib.h
shmem.o: /home/tiju/Silverbox-OS/include/ipc.h
shmem.o: /home/tiju/Silverbox-OS/include/os/mutex.h
shmem.o: /home/tiju/Silverbox-OS/include/stdlib.h
name.o: /home/tiju/Silverbox-OS/include/oslib.h
name.o: /home/tiju/Silverbox-OS/include/types.h
name.o: /home/tiju/Silverbox-OS/include/stddef.h
name.o: /home/tiju/Silverbox-OS/include/stdbool.h
name.o: /home/tiju/Silverbox-OS/include/ipc.h
name.o: /home/tiju/Silverbox-OS/include/os/mutex.h
name.o: /home/tiju/Silverbox-OS/include/os/services.h
name.o: /home/tiju/Silverbox-OS/include/os/device.h
name.o: /home/tiju/Silverbox-OS/include/os/region.h
name.o: /home/tiju/Silverbox-OS/include/string.h name.h
exceptions.o: addr_space.h /home/tiju/Silverbox-OS/include/os/bitmap.h
exceptions.o: /home/tiju/Silverbox-OS/include/stddef.h list.h
exceptions.o: /home/tiju/Silverbox-OS/include/stdbool.h phys_alloc.h
exceptions.o: pagersrv.h /home/tiju/Silverbox-OS/include/types.h
exceptions.o: /home/tiju/Silverbox-OS/include/os/region.h
exceptions.o: /home/tiju/Silverbox-OS/include/oslib.h
exceptions.o: /home/tiju/Silverbox-OS/include/ipc.h
exceptions.o: /home/tiju/Silverbox-OS/include/os/mutex.h
exceptions.o: /home/tiju/Silverbox-OS/include/string.h
sbrk.o: /home/tiju/Silverbox-OS/include/oslib.h
sbrk.o: /home/tiju/Silverbox-OS/include/types.h
sbrk.o: /home/tiju/Silverbox-OS/include/stddef.h
sbrk.o: /home/tiju/Silverbox-OS/include/stdbool.h
sbrk.o: /home/tiju/Silverbox-OS/include/ipc.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/mutex.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/memory.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/services.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/device.h
sbrk.o: /home/tiju/Silverbox-OS/include/os/region.h
