.ifndef GRUB_H
.set GRUB_H, 1

.equ MULTIBOOT_PAGE_ALIGN,	0x01
.equ MULTIBOOT_MEMORY_INFO,	0x02
.equ MULTIBOOT_AOUT_KLUDGE,	0x10000
.equ MULTIBOOT_HEADER_MAGIC,	0x1BADB002
.equ MULTIBOOT_HEADER_FLAGS,	MULTIBOOT_PAGE_ALIGN | MULTIBOOT_MEMORY_INFO | MULTIBOOT_AOUT_KLUDGE
.equ MULTIBOOT_CHECKSUM,	-(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS)

.endif
