.ifndef GRUB_H
.set GRUB_H, 1

#define MULTIBOOT_PAGE_ALIGN	0x01
#define MULTIBOOT_MEMORY_INFO	0x02
#define MULTIBOOT_VIDEO_TABLE	0x04
#define MULTIBOOT_AOUT_KLUDGE	0x10000
#define MULTIBOOT_HEADER_MAGIC	0x1BADB002
#define MULTIBOOT_HEADER_FLAGS	MULTIBOOT_PAGE_ALIGN | MULTIBOOT_MEMORY_INFO | MULTIBOOT_VIDEO_TABLE
#define MULTIBOOT_CHECKSUM	-(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS)

#define MULTIBOOT_LINEAR_GFX	0
#define MULTIBOOT_EGA_TEXT	1

#define MULTIBOOT_EGA_WIDTH	0
#define MULTIBOOT_EGA_HEIGHT	0
#define MULTIBOOT_EGA_DEPTH	0
.endif
