DIRS	=fs
SRC     =addr_space.c phys_alloc.c initsrv.c name.c \
	exceptions.c sbrk.c init.c paging.c resources.c
#	fs/vfs.c fs/fat_lib.c fs/fat_fs.c fs/fat_alloc.c \
#	fs/vfs_ops.c

OUTPUT	=pagersrv.exe
INSTALL_DIR=programs/

include apps.mk
