SRC     =memchr.c memcpy.c memset.c strcpy.c strlen.c strcat.c \
	strncpy.c strncat.c memmove.c strcmp.c strncmp.c memcmp.c \
	strchr.c strrchr.c strtok.c strpbrk.c strspn.c strstr.c strcspn.c
OBJ     =$(SRC:.c=.o)
OPT_FLG =-O2
CLEAN   =$(OBJ)

all: $(OBJ)
	@cp *.o ..
include ../../vars.mk
# DO NOT DELETE

memchr.o: /home/tiju/silverbox-os/include/string.h
memchr.o: /home/tiju/silverbox-os/include/stddef.h
memcpy.o: /home/tiju/silverbox-os/include/string.h
memcpy.o: /home/tiju/silverbox-os/include/stddef.h
memset.o: /home/tiju/silverbox-os/include/string.h
memset.o: /home/tiju/silverbox-os/include/stddef.h
strcpy.o: /home/tiju/silverbox-os/include/string.h
strcpy.o: /home/tiju/silverbox-os/include/stddef.h
strlen.o: /home/tiju/silverbox-os/include/string.h
strlen.o: /home/tiju/silverbox-os/include/stddef.h
strcat.o: /home/tiju/silverbox-os/include/string.h
strcat.o: /home/tiju/silverbox-os/include/stddef.h
strncpy.o: /home/tiju/silverbox-os/include/string.h
strncpy.o: /home/tiju/silverbox-os/include/stddef.h
strncat.o: /home/tiju/silverbox-os/include/string.h
strncat.o: /home/tiju/silverbox-os/include/stddef.h
memmove.o: /home/tiju/silverbox-os/include/string.h
memmove.o: /home/tiju/silverbox-os/include/stddef.h
strcmp.o: /home/tiju/silverbox-os/include/string.h
strcmp.o: /home/tiju/silverbox-os/include/stddef.h
strncmp.o: /home/tiju/silverbox-os/include/string.h
strncmp.o: /home/tiju/silverbox-os/include/stddef.h
memcmp.o: /home/tiju/silverbox-os/include/string.h
memcmp.o: /home/tiju/silverbox-os/include/stddef.h
strchr.o: /home/tiju/silverbox-os/include/string.h
strchr.o: /home/tiju/silverbox-os/include/stddef.h
strrchr.o: /home/tiju/silverbox-os/include/string.h
strrchr.o: /home/tiju/silverbox-os/include/stddef.h
strtok.o: /home/tiju/silverbox-os/include/string.h
strtok.o: /home/tiju/silverbox-os/include/stddef.h
strpbrk.o: /home/tiju/silverbox-os/include/string.h
strpbrk.o: /home/tiju/silverbox-os/include/stddef.h
strspn.o: /home/tiju/silverbox-os/include/string.h
strspn.o: /home/tiju/silverbox-os/include/stddef.h
strstr.o: /home/tiju/silverbox-os/include/string.h
strstr.o: /home/tiju/silverbox-os/include/stddef.h
strcspn.o: /home/tiju/silverbox-os/include/string.h
strcspn.o: /home/tiju/silverbox-os/include/stddef.h
