SRC     =memchr.c memcpy.c memset.c strcpy.c strlen.c strcat.c \
	strncpy.c strncat.c memmove.c strcmp.c strncmp.c memcmp.c \
	strchr.c strrchr.c strtok.c strpbrk.c strspn.c strstr.c strcspn.c
OBJ     =$(SRC:.c=.o)
OPT_FLG =-O2

all: $(OBJ)

include ../../Makefile.inc
include ../../vars.mk

clean:
	rm -f *.o

# DO NOT DELETE

memchr.o: /home/tiju/Silverbox-OS/include/string.h
memchr.o: /home/tiju/Silverbox-OS/include/stddef.h
memcpy.o: /home/tiju/Silverbox-OS/include/string.h
memcpy.o: /home/tiju/Silverbox-OS/include/stddef.h
memset.o: /home/tiju/Silverbox-OS/include/string.h
memset.o: /home/tiju/Silverbox-OS/include/stddef.h
strcpy.o: /home/tiju/Silverbox-OS/include/string.h
strcpy.o: /home/tiju/Silverbox-OS/include/stddef.h
strlen.o: /home/tiju/Silverbox-OS/include/string.h
strlen.o: /home/tiju/Silverbox-OS/include/stddef.h
strcat.o: /home/tiju/Silverbox-OS/include/string.h
strcat.o: /home/tiju/Silverbox-OS/include/stddef.h
strncpy.o: /home/tiju/Silverbox-OS/include/string.h
strncpy.o: /home/tiju/Silverbox-OS/include/stddef.h
strncat.o: /home/tiju/Silverbox-OS/include/string.h
strncat.o: /home/tiju/Silverbox-OS/include/stddef.h
memmove.o: /home/tiju/Silverbox-OS/include/string.h
memmove.o: /home/tiju/Silverbox-OS/include/stddef.h
strcmp.o: /home/tiju/Silverbox-OS/include/string.h
strcmp.o: /home/tiju/Silverbox-OS/include/stddef.h
strncmp.o: /home/tiju/Silverbox-OS/include/string.h
strncmp.o: /home/tiju/Silverbox-OS/include/stddef.h
memcmp.o: /home/tiju/Silverbox-OS/include/string.h
memcmp.o: /home/tiju/Silverbox-OS/include/stddef.h
strchr.o: /home/tiju/Silverbox-OS/include/string.h
strchr.o: /home/tiju/Silverbox-OS/include/stddef.h
strrchr.o: /home/tiju/Silverbox-OS/include/string.h
strrchr.o: /home/tiju/Silverbox-OS/include/stddef.h
strtok.o: /home/tiju/Silverbox-OS/include/string.h
strtok.o: /home/tiju/Silverbox-OS/include/stddef.h
strpbrk.o: /home/tiju/Silverbox-OS/include/string.h
strpbrk.o: /home/tiju/Silverbox-OS/include/stddef.h
strspn.o: /home/tiju/Silverbox-OS/include/string.h
strspn.o: /home/tiju/Silverbox-OS/include/stddef.h
strstr.o: /home/tiju/Silverbox-OS/include/string.h
strstr.o: /home/tiju/Silverbox-OS/include/stddef.h
strcspn.o: /home/tiju/Silverbox-OS/include/string.h
strcspn.o: /home/tiju/Silverbox-OS/include/stddef.h
