include ../../../Makefile.inc

.PHONY: all tests install clean

ROOT_DIR=../../..
SRC     =cqueue.c sbarray.c sbhash.c sbstring.c circbuffer.c
OBJ     =$(SRC:.c=.o)

all: $(OBJ)

install:

tests:

clean:
	rm -f *.o

include ../../../Makefile_post.inc
