SRC	=clearerr.c do_printf.c feof.c ferror.c fflush.c fgetc.c fprintf.c \
        fputc.c fputs.c fseek.c ftell.c getc.c getchar.c gets.c perror.c \
        printf.c putc.c putchar.c puts.c rewind.c setvbuf.c sprintf.c \
        stdio_init.c vfprintf.c vprintf.c vsprintf.c fopen.c fread.c \
	fclose.c

OBJ     =$(SRC:.c=.o)
OPT_FLG =-O0

all: $(OBJ)

include ../../Makefile.inc
include ../../vars.mk

clean:
	rm -f *.o

# DO NOT DELETE

clearerr.o: /home/tiju/Silverbox-OS/include/stdio.h
clearerr.o: /home/tiju/Silverbox-OS/include/stddef.h
clearerr.o: /home/tiju/Silverbox-OS/include/stdarg.h
do_printf.o: /home/tiju/Silverbox-OS/include/stdio.h
do_printf.o: /home/tiju/Silverbox-OS/include/stddef.h
do_printf.o: /home/tiju/Silverbox-OS/include/stdarg.h
do_printf.o: /home/tiju/Silverbox-OS/include/stdlib.h
do_printf.o: /home/tiju/Silverbox-OS/include/string.h
do_printf.o: /home/tiju/Silverbox-OS/include/ctype.h
feof.o: /home/tiju/Silverbox-OS/include/stdio.h
feof.o: /home/tiju/Silverbox-OS/include/stddef.h
feof.o: /home/tiju/Silverbox-OS/include/stdarg.h
ferror.o: /home/tiju/Silverbox-OS/include/stdio.h
ferror.o: /home/tiju/Silverbox-OS/include/stddef.h
ferror.o: /home/tiju/Silverbox-OS/include/stdarg.h
fflush.o: /home/tiju/Silverbox-OS/include/stdio.h
fflush.o: /home/tiju/Silverbox-OS/include/stddef.h
fflush.o: /home/tiju/Silverbox-OS/include/stdarg.h
fflush.o: /home/tiju/Silverbox-OS/include/os/console.h
fflush.o: /home/tiju/Silverbox-OS/include/types.h
fflush.o: /home/tiju/Silverbox-OS/include/stdbool.h
fgetc.o: /home/tiju/Silverbox-OS/include/stdio.h
fgetc.o: /home/tiju/Silverbox-OS/include/stddef.h
fgetc.o: /home/tiju/Silverbox-OS/include/stdarg.h
fgetc.o: /home/tiju/Silverbox-OS/include/os/console.h
fgetc.o: /home/tiju/Silverbox-OS/include/types.h
fgetc.o: /home/tiju/Silverbox-OS/include/stdbool.h
fprintf.o: /home/tiju/Silverbox-OS/include/stdio.h
fprintf.o: /home/tiju/Silverbox-OS/include/stddef.h
fprintf.o: /home/tiju/Silverbox-OS/include/stdarg.h
fputc.o: /home/tiju/Silverbox-OS/include/stdio.h
fputc.o: /home/tiju/Silverbox-OS/include/stddef.h
fputc.o: /home/tiju/Silverbox-OS/include/stdarg.h
fputc.o: /home/tiju/Silverbox-OS/include/stdlib.h
fputc.o: /home/tiju/Silverbox-OS/include/string.h
fputc.o: /home/tiju/Silverbox-OS/include/os/console.h
fputc.o: /home/tiju/Silverbox-OS/include/types.h
fputc.o: /home/tiju/Silverbox-OS/include/stdbool.h
fputs.o: /home/tiju/Silverbox-OS/include/stdio.h
fputs.o: /home/tiju/Silverbox-OS/include/stddef.h
fputs.o: /home/tiju/Silverbox-OS/include/stdarg.h
fputs.o: /home/tiju/Silverbox-OS/include/string.h
fseek.o: /home/tiju/Silverbox-OS/include/stdio.h
fseek.o: /home/tiju/Silverbox-OS/include/stddef.h
fseek.o: /home/tiju/Silverbox-OS/include/stdarg.h
fseek.o: /home/tiju/Silverbox-OS/include/errno.h
ftell.o: /home/tiju/Silverbox-OS/include/stdio.h
ftell.o: /home/tiju/Silverbox-OS/include/stddef.h
ftell.o: /home/tiju/Silverbox-OS/include/stdarg.h
ftell.o: /home/tiju/Silverbox-OS/include/errno.h
getc.o: /home/tiju/Silverbox-OS/include/stdio.h
getc.o: /home/tiju/Silverbox-OS/include/stddef.h
getc.o: /home/tiju/Silverbox-OS/include/stdarg.h
getchar.o: /home/tiju/Silverbox-OS/include/stdio.h
getchar.o: /home/tiju/Silverbox-OS/include/stddef.h
getchar.o: /home/tiju/Silverbox-OS/include/stdarg.h
gets.o: /home/tiju/Silverbox-OS/include/stdio.h
gets.o: /home/tiju/Silverbox-OS/include/stddef.h
gets.o: /home/tiju/Silverbox-OS/include/stdarg.h
perror.o: /home/tiju/Silverbox-OS/include/stdio.h
perror.o: /home/tiju/Silverbox-OS/include/stddef.h
perror.o: /home/tiju/Silverbox-OS/include/stdarg.h
perror.o: /home/tiju/Silverbox-OS/include/errno.h
printf.o: /home/tiju/Silverbox-OS/include/stdio.h
printf.o: /home/tiju/Silverbox-OS/include/stddef.h
printf.o: /home/tiju/Silverbox-OS/include/stdarg.h
putc.o: /home/tiju/Silverbox-OS/include/stdio.h
putc.o: /home/tiju/Silverbox-OS/include/stddef.h
putc.o: /home/tiju/Silverbox-OS/include/stdarg.h
putchar.o: /home/tiju/Silverbox-OS/include/stdio.h
putchar.o: /home/tiju/Silverbox-OS/include/stddef.h
putchar.o: /home/tiju/Silverbox-OS/include/stdarg.h
puts.o: /home/tiju/Silverbox-OS/include/stdio.h
puts.o: /home/tiju/Silverbox-OS/include/stddef.h
puts.o: /home/tiju/Silverbox-OS/include/stdarg.h
rewind.o: /home/tiju/Silverbox-OS/include/stdio.h
rewind.o: /home/tiju/Silverbox-OS/include/stddef.h
rewind.o: /home/tiju/Silverbox-OS/include/stdarg.h
setvbuf.o: /home/tiju/Silverbox-OS/include/stdio.h
setvbuf.o: /home/tiju/Silverbox-OS/include/stddef.h
setvbuf.o: /home/tiju/Silverbox-OS/include/stdarg.h
setvbuf.o: /home/tiju/Silverbox-OS/include/stdlib.h
setvbuf.o: /home/tiju/Silverbox-OS/include/errno.h
sprintf.o: /home/tiju/Silverbox-OS/include/stdio.h
sprintf.o: /home/tiju/Silverbox-OS/include/stddef.h
sprintf.o: /home/tiju/Silverbox-OS/include/stdarg.h
stdio_init.o: /home/tiju/Silverbox-OS/include/stdio.h
stdio_init.o: /home/tiju/Silverbox-OS/include/stddef.h
stdio_init.o: /home/tiju/Silverbox-OS/include/stdarg.h
vfprintf.o: /home/tiju/Silverbox-OS/include/stdio.h
vfprintf.o: /home/tiju/Silverbox-OS/include/stddef.h
vfprintf.o: /home/tiju/Silverbox-OS/include/stdarg.h
vprintf.o: /home/tiju/Silverbox-OS/include/stdio.h
vprintf.o: /home/tiju/Silverbox-OS/include/stddef.h
vprintf.o: /home/tiju/Silverbox-OS/include/stdarg.h
vsprintf.o: /home/tiju/Silverbox-OS/include/stdio.h
vsprintf.o: /home/tiju/Silverbox-OS/include/stddef.h
vsprintf.o: /home/tiju/Silverbox-OS/include/stdarg.h
