SRC     =strtol.c malloc.c algo.c
OBJ     =$(SRC:.c=.o)
OPT_FLG =-O0
CLEAN   =$(OBJ)

all: $(OBJ)

include ../../vars.mk
# DO NOT DELETE

strtol.o: /home/tiju/Silverbox-OS/include/ctype.h
strtol.o: /home/tiju/Silverbox-OS/include/stddef.h
strtol.o: /home/tiju/Silverbox-OS/include/stdlib.h
malloc.o: /home/tiju/Silverbox-OS/include/types.h
malloc.o: /home/tiju/Silverbox-OS/include/stddef.h
malloc.o: /home/tiju/Silverbox-OS/include/stdbool.h
malloc.o: /home/tiju/Silverbox-OS/include/assert.h
malloc.o: /home/tiju/Silverbox-OS/include/stdio.h
malloc.o: /home/tiju/Silverbox-OS/include/stdarg.h
malloc.o: /home/tiju/Silverbox-OS/include/string.h
algo.o: /home/tiju/Silverbox-OS/include/stdlib.h
algo.o: /home/tiju/Silverbox-OS/include/stddef.h
