SRC     =strtol.c malloc.c algo.c
OBJ     =$(SRC:.c=.o)
OPT_FLG =-O0
CLEAN   =$(OBJ)

all: $(OBJ)

include ../../vars.mk
# DO NOT DELETE

strtol.o: /home/tiju/silverbox-os/include/ctype.h
strtol.o: /home/tiju/silverbox-os/include/stddef.h
strtol.o: /home/tiju/silverbox-os/include/stdlib.h
malloc.o: /home/tiju/silverbox-os/include/types.h
malloc.o: /home/tiju/silverbox-os/include/stddef.h
malloc.o: /home/tiju/silverbox-os/include/stdbool.h
malloc.o: /home/tiju/silverbox-os/include/assert.h
malloc.o: /home/tiju/silverbox-os/include/stdio.h
malloc.o: /home/tiju/silverbox-os/include/stdarg.h
malloc.o: /home/tiju/silverbox-os/include/string.h
algo.o: /home/tiju/silverbox-os/include/stdlib.h
algo.o: /home/tiju/silverbox-os/include/stddef.h
