#include <errno.h>

const char * const _errno_reasons[80] = {
"No error.",
"Argument list too long.",
"Permission denied.",
"Address in use.",
"Address not available.",
"Address family not supported.",
"Resource unavailable, try again.",
"Connection already in progress.",
"Bad file descriptor.",
"Bad message.",
"Device or resource busy.",
"Operation canceled.",
"No child processes.",
"Connection aborted.",
"Connection refused.",
"Connection reset.",
"Resource deadlock would occur.",
"Destination address required.",
"Mathematics argument out of domain of function.",
"Disk quota exceeded.",
"File exists.",
"Bad address.",
"File too large.",
"Host is unreachable.",
"Identifier removed.",
"Illegal byte sequence.",
"Operation in progress.",
"Interrupted function.",
"Invalid argument.",
"I/O error.",
"Socket is connected.",
"Is a directory.",
"Too many levels of symbolic links.",
"Too many open files.",
"Too many links.",
"Message too large.",
"Multihop attempted.",
"Filename too long.",
"Network is down.",
"Connection aborted by network.",
"Network unreachable.",
"Too many files open in system.",
"No buffer space available.",
"No message is available on the STREAM head read queue.",
"No such device.",
"No such file or directory.",
"Executable file format error.",
"No locks available.",
"Link has been severed.",
"Not enough space.",
"No message of the desired type.",
"Protocol not available.",
"No space left on device.",
"No STREAM resources.",
"Not a STREAM.",
"Function not supported.",
"The socket is not connected.",
"Not a directory.",
"Directory not empty.",
"Not a socket.",
"Not supported.",
"Inappropriate I/O control operation.",
"No such device or address.",
"Operation not supported on socket.",
"Value too large to be stored in data type.",
"Operation not permitted.",
"Broken pipe.",
"Protocol error.",
"Protocol not supported.",
"Protocol wrong type for socket.",
"Result too large.",
"Read-only file system.",
"Invalid seek.",
"No such process.",
"Stale file handle.",
"Stream timeout.",
"Connection timed out.",
"Text file busy.",
"Operation would block.",
"Cross-device link." 
};
