SRC     =errno.c
OBJ     =$(SRC:.c=.o)
OPT_FLG =-O2

all: $(OBJ)

include ../../Makefile.inc
include ../../vars.mk

clean:
	rm -f *.o

# DO NOT DELETE

errno.o: /home/tiju/Silverbox-OS/include/errno.h
