SRC     =syscalls.c
OBJ     =$(SRC:.c=.o)
OPT_FLG =-O0
CLEAN   =$(OBJ)

all: $(OBJ)

include ../../vars.mk
# DO NOT DELETE

syscalls.o: /home/tiju/Silverbox-OS/include/oslib.h
syscalls.o: /home/tiju/Silverbox-OS/include/types.h
syscalls.o: /home/tiju/Silverbox-OS/include/stddef.h
syscalls.o: /home/tiju/Silverbox-OS/include/stdbool.h
syscalls.o: /home/tiju/Silverbox-OS/include/ipc.h
syscalls.o: /home/tiju/Silverbox-OS/include/os/mutex.h
